name: Publish to Packagist

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: mbstring, dom, fileinfo

    - name: Get composer cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache composer dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run tests
      run: composer test

    - name: Archive package
      run: |
        mkdir -p dist
        tar -czf dist/package.tar.gz --exclude=dist --exclude=.git --exclude=vendor --exclude=node_modules .

    - name: Upload package archive
      uses: actions/upload-artifact@v3
      with:
        name: package-${{ github.event.release.tag_name }}
        path: dist/package.tar.gz
